### PR TITLE
#1166 validate config

### PR DESCRIPTION
**Pull request by kyazdani42**
@alex-courtis there are a few edge cases that were not covered
somehow https://github.com/kyazdani42/nvim-tree.lua/issues/1194 but i cannot reproduce
and when an option can have different types (such a view.width/view.height)

### CODE REVIEW

**Comment by alex-courtis** [comment]
> somehow #1194 but i cannot reproduce

That's a use case I did not account for: value table with defaults, rather than empty.

I'll think about options. Perhaps the ignore list is still a good idea.

**Comment by alex-courtis** [comment]
> and when an option can have different types (such a view.width/view.height)

I'm not sure that is a [good idea](https://github.com/kyazdani42/nvim-tree.lua/issues/new/choose), however we can work with it.

**Comment by alex-courtis** [comment]
Let's try this again:
* functions are allowed as values; I have added a warning to the doc
* integer indexed tables are not checked, as they are not strongly typed and have variable length contents

**Comment by alex-courtis** [comment]
Tested:
* empty options
* default options
* my setup
* #1194
* function as per https://github.com/kyazdani42/nvim-tree.lua/pull/1177#issuecomment-1107832916

**Review by alex-courtis — APPROVED** [review]

**Comment by kyazdani42** [comment]
let see if this works :smile:

**Pull request merged**
