### PR TITLE
#1253 only pad git icons when they are present

### LINKED ISSUE #1253: Trailing whitespaces of file and folder names
### Description

I use LunarVim, and I have a linter activated that warns me of lines with trailing whitespaces.

According to this, it seems that now **NvimTree.lua** is putting trailing whitespaces at the end of everything, to solve this I started to search through the last commits of **NvimTree.lua** until I got to the one where this was not happening to fix it temporarily... the commit is `ec888d08ce80bc3ee6efde6405f9bb564f897add`

Temporarily deactivate the flashlight to check more manually this...
```sh
:match ExtraWhitespace /\s\+$/
:highlight ExtraWhitespace guibg=red
```

And indeed, there seem to be blank spaces at the end of lines

Screenshot from 2022-05-09 22-53-06

### Neovim version

```text
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

Linux Ubuntu 20.04.4 LTS

### nvim-tree version

47732b6

### Minimal config

```lua
Occurs with LunarVim vanilla
```

### Steps to reproduce

Occurs with LunarVim vanilla

### Expected behavior

_No response_

### Actual behavior

_No response_

### PR DESCRIPTION
**Pull request by alex-courtis**
closes #1253 

should not interfere with #1242

### CODE REVIEW

**Review by kyazdani42 — APPROVED** [review]

**Comment by kyazdani42** [comment]
This was causing issues on folders when git placement was "before"

**Comment by kyazdani42** [comment]
better fix in 7293f8dc709f9f207e3d71338599649dc3d76996

**Comment by alex-courtis** [comment]
Thanks for fixing :)

**Comment by alex-courtis** [comment]
Still not quite right: https://github.com/kyazdani42/nvim-tree.lua/issues/1253

We are seeing whitespace in all cases except when the git icon is shown after. It's the space added in `Builder:_format_line` that is problematic here.

**Pull request merged**
