### PR TITLE
fix issue with data race when opening with luatreefindfile

### LINKED ISSUE #146: LuaTreeFindFile positions cursor at the top
Cursor should be positioned to the current file opened and not the top

Exists on this commit ba4dac1e5904ddf91f3993bb9119d0487cb16a1d

### PR DESCRIPTION
**Pull request by kyazdani42**
fixes #146

### CODE REVIEW

**Comment by kristijanhusak** [comment]
After this PR, when tree is opened, and you try to do `:LuaTreeFindFile`, it doesn't do anything. Before it focused the tree window on the given file.

**Comment by kyazdani42** [comment]
@kristijanhusak can you provide more information ? Works for me.

**Comment by kristijanhusak** [comment]
Here the gif:

[
luatree
](url)

I executed `LuaTreeFindFile`, but tree didn't got the focus.

**Comment by kyazdani42** [comment]
i pushed a small fix, the tree cursor properly updates but it doesn't focus the tree though. Tell me if it's all ok for you

**Comment by kristijanhusak** [comment]
I hoped to get it to focus, at least that was the old functionality.

**Comment by kyazdani42** [comment]
Fixed in master, please tell me if there are other things that went wrong !

**Comment by kristijanhusak** [comment]
@kyazdani42 works great now, thanks!

**Pull request merged**
