### PR TITLE
fix(#1529): ensure tree window exists before closing

### LINKED ISSUE #1529: View float: Invalid window id
### Description

I set the floating window open/close to `<leader>e`. But if I close the window with this key combination, I get an error message.

### Neovim version

```text
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

Linux arch 5.19.1-arch2-1

### nvim-tree version

81eb718

### Minimal config

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "kyazdani42/nvim-tree.lua",
      "kyazdani42/nvim-web-devicons",
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  local opts = { noremap = true, silent = true }
  vim.g.mapleader = " "
  vim.keymap.set("", "<Space>", "<Nop>", opts)
  vim.keymap.set("n", "<leader>e", ":NvimTreeRefresh<CR>:NvimTreeToggle<CR>", opts)
  
  require("nvim-tree").setup {
    sort_by = "case_sensitive",
    sync_root_with_cwd = true,
    respect_buf_cwd = true,
  
    update_focused_file = {
      enable = true,
      update_root = true
    },
    view = {
      float = {
        enable = true
      }
    }
  }
end
```

### Steps to reproduce

1. nvim -nu ~/nvt-min.lua
2. `:e any_file`
3. Press `<space>e`
4. Press `<space>e`

### Expected behavior

`:NvimTreeToggle` should open/close file tree without error messages.

### Actual behavior

```
Error executing Lua callback: ...e/pack/packer/start/nvim-tree.lua/lua/nvim-tree/view.lua:195: Invalid window id: 1005                                      
stack traceback:
        [C]: in function 'nvim_win_close'
        ...e/pack/packer/start/nvim-tree.lua/lua/nvim-tree/view.lua:195: in function 'close'
        ...n/site/pack/packer/start/nvim-tree.lua/lua/nvim-tree.lua:76: in function 'toggle'
        ...n/site/pack/packer/start/nvim-tree.lua/lua/nvim-tree.lua:304: in function <...n/site/pack/packer/start/nvim-tree.lua/lua/nvim-tree.lua:303>
```

### PR DESCRIPTION
**Pull request by alex-courtis**
resolves #1529

### CODE REVIEW

**Comment by alex-courtis** [comment]
- [ ] Please review @Khrees.
- [ ] Please test @solipfuct.

**Comment by solipfuct** [comment]
@alex-courtis fixed for me.

**Review by Khrees — COMMENTED** [review]
@alex-courtis Looks good to me.

**Comment by alex-courtis** [comment]
Thanks for test/review.

**Pull request merged**
