### PR TITLE
Feature: open file/folder with default system application

### PR DESCRIPTION
**Pull request by xeluxee**
This feature is equivalent to "reveal" in nerdtree or "execute_system" in defx.

Open a file with default system application by pressing `s`
Open a folder with system file manager by pressing `s`

Tested on Linux.
Should work also on MacOS, Windows, Windows Cygwin and systems using `xdg-open`, like FreeBSD.

### CODE REVIEW

**Comment by xeluxee** [comment]
Related issues: #537, #469, #409, #320, #274, #226
Also changes introduced with PR #411 are removed, beacuse now it's enough to press 's' on a file/folder

**Comment by xeluxee** [comment]
> Tested on Linux.
> Should work also on MacOS, Windows, Windows Cygwin and systems using `xdg-open`, like FreeBSD.

Now tested on Windows too.

**Review by kyazdani42 — APPROVED** [review]

**Comment by cseelus** [comment]
Works perfectly on macOS 11, thanks!

**Comment by xeluxee** [comment]
No worries, nice to know that!

**Pull request merged**
