### PR TITLE
#1099 search obeys active ignore filters

### LINKED ISSUE #1099: Search Does Not Obey Ignored
#1092 broke functionality: search will return ignored

Currently 3 flavours of ignored: git_ignored, dotfiles and custom

Search could ignore based on the current toggled state of the ignores.

There is a performance concern searching large directories e.g. node_modules

Possible solutions:

1. find-file take a new flag indicating that it should not find ignored (performance issue)
1. search invokes filters.should_ignore before recursing subdirectories

### PR DESCRIPTION
**Pull request by alex-courtis**
#1099 solution 2

closes #1099

### CODE REVIEW

**Comment by alex-courtis** [comment]
@be-ndee I would be grateful for your feedback / testing.

Once again, please accept my apologies for breaking the functionality.

**Review by kyazdani42 — APPROVED** [review]
let's @be-ndee test this before we merge :)

**Comment by alex-courtis** [comment]
> let's @be-ndee test this before we merge :)

Whoops... I didn't see this comment before I merged.

We can revert ;)

**Comment by kyazdani42** [comment]
That's okay, lets see if we have some feedback first :)

**Comment by be-ndee** [comment]
Sorry, I'm quite busy at the moment... 

@alex-courtis there is no need for apologizing, but apologies are accepted :D

**Pull request merged**
