### PR TITLE
fix: disable highlighting 'number' when CursorLine is enabled

### LINKED ISSUE #929: Signcolumn bg showing on selected file
**OS**
Operation system's name and version
NixOS 22.05.20220202.f85152d (Quokka)

**Neovim version**
output of `nvim --version`
NVIM v0.7.0-dev
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by nixbld

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/fn8i1l9hlp8v38akrskm77w2wzyxdmcl-neovim-unwrapped-master/share/nvim
"

Run :checkhealth for more info

**Nvim-tree version**
nvim-tree branch, commit or tag number
commit 99d65afd6ef05cc57f835451126e5c44db03cef1

**Describe the bug**
NvimTree shows Signcolumn highlight group's guibg color on the selected file/folder entry.

**To Reproduce**
Steps to reproduce the behavior
1. Open Nvimtree
2. See the signcolumn getting highlighted on the active entry

**Expected behavior**
Not sure if this is intentional, but I would expect it to not show the signcolumn's bg since it seems to be reserved for only diagnostics.
image

### PR DESCRIPTION
**Pull request by boppyt**
Fixes #929

### CODE REVIEW

**Comment by boppyt** [comment]
**Before the patch**
before-patch

**After the patch**
after-patch

**Review by kyazdani42 — APPROVED** [review]
thanks :)

**Comment by wookayin** [comment]
From this patch (230a61d) neovim 0.6.0+ is required. Until this neovim 0.5.0 was working fine.

**Comment by eeeXun** [comment]
Could you export it to part of config? I only wanna highlight number.

**Comment by kyazdani42** [comment]
in the readme: `you can update window options for the tree by setting require"nvim-tree.view".View.winopts.MY_OPTION = MY_OPTION_VALUE`.

**Comment by eeeXun** [comment]
@kyazdani42 Got it. But still, I wanna put it under `require"nvim-tree".setup.view`. Is it not recommended?

**Comment by kyazdani42** [comment]
it is not. I might move all option configuration through an helper function to avoid people accessing the view directly.

**Pull request merged**
