### PR TITLE
feat: add float autoclose option

### PR DESCRIPTION
**Pull request by emmanueltouzery**
I like the float mode of the treeview, however I'd like it not to autoclose when the popup loses focus.

So I've added an option to that effect.

### CODE REVIEW

**Comment by alex-courtis** [comment]
I asked for that to be [unconditionally added](https://github.com/kyazdani42/nvim-tree.lua/pull/1462#pullrequestreview-1056510957) as I didn't consider the use case that the user desires this functionality.

**Review by alex-courtis — CHANGES_REQUESTED** [review]
`view.float.autoclose = true`

Tested OK:
* window focus is changed

Needs work:
* `actions.open_file.quit_on_open = false`: float closes when opening file

**Comment by emmanueltouzery** [comment]
Yes, the `close_on_open` was hardcoded as per the original PR https://github.com/kyazdani42/nvim-tree.lua/pull/1462 -- the comment was that it didn't work properly otherwise.

This is also documented:
```
*nvim-tree.view.float.enable*
        Display nvim-tree window as float (enforces |nvim-tree.actions.open_file.quit_on_open| if set).
          Type: `boolean`, Default: `false`
```
I didn't have that much testing time with the feature yet, so I'm not sure what I'd prefer yet. Right now I think that I'd like the setup of this PR (don't close on focus loss, close on open).

I understand that the settings as set up by this PR are confusing.

What about if we rename this setting to `auto_close_when_unfocused`? Or maybe `auto_close_on_focus_loss`? And we reserve the option to potentially one day respect `quit_on_open` also for the floating configuration, which I view as an independent thing that also wasn't supported so far.

**Comment by alex-courtis** [comment]
> This is also documented:

Good catch! That can be changed.

> I didn't have that much testing time with the feature yet, so I'm not sure what I'd prefer yet. Right now I think that I'd like the setup of this PR (don't close on focus loss, close on open).
> 
> I understand that the settings as set up by this PR are confusing.
> 
> What about if we rename this setting to auto_close_when_unfocused? Or maybe auto_close_on_focus_loss? And we reserve the option to potentially one day respect quit_on_open also for the floating configuration, which I view as an independent thing that also wasn't supported so far.

We can keep it simple and do it now: floating window respects both `actions.open_file.quit_on_open` and `view.float.autoclose` now. No need for another option.

`autoclose` -> `quit_on_focus_loss` might be the clearest, consistent option.

**Comment by alex-courtis** [comment]
RE defaults: users will experience disruption if they relied on the implicit `quit_on_open`, however I think that is a reasonable change for a newly released feature.

**Comment by emmanueltouzery** [comment]
I don't understand the disruption? `quit_on_open` didn't work for the floating window setup, and still doesn't? So it seems to me there is no change?

I'll update the PR with the setting rename.

**Comment by alex-courtis** [comment]
> I don't understand the disruption? `quit_on_open` didn't work for the floating window setup, and still doesn't? So it seems to me there is no change?

The implicit `quit_on_open` is always firing, regardless of `autoclose`. My proposal is that we always respect the user's `quit_on_open` setting for floating windows. This will be a more predictable user experience and offers the full range of behaviour choices.

Making both changes now will be less disruptive and I would be very greatful if you could make this change in this PR.

**Comment by emmanueltouzery** [comment]
ok, i'll research what is the breakage that the quit_on_open locking was supposed to workaround. i think fixing that shouldn't be too hard.

**Comment by emmanueltouzery** [comment]
OK, I've updated the PR. I do not understand what was the issue with quit_on_open. I removed the setting blocking it and.. it worked right away for me. I couldn't find any issue... It seems to work just fine for me.

It does turn out there can be a conflict between both options. If you say `quit_on_focus_loss=true` but `quit_on_open=false`... i mean when we open a file, we focus it. Therefore it's a focus loss. But the three other cases are clear.

quit_on_focus_loss=true
quit_on_open=true
=> no problem, clear what should happen (and it's the current behavior)

quit_on_focus_loss=false
quit_on_open=true
=> ok, clear what should happen

quit_on_focus_loss=false
quit_on_open=false
=> clear

quit_on_focus_loss=true
quit_on_open=false
=> ambiguous, quit_on_focus_loss wins and effectively we have quit_on_open=true enforced

quit_on_focus_loss=false
quit_on_open=false
=> ok, clear what should happen

I've tested the four cases, everything looks good to me. I intend to use true+true for now, maybe i'll switch to quit_on_focus_loss=false+quit_on_open=true, I'll see. But so far I can't see any issues.

**Comment by emmanueltouzery** [comment]
Ok, I found an issue. The tree contents are not updated when we switch buffers. I'll check it out.

**Comment by emmanueltouzery** [comment]
false alert: I needed update_focused_file.update_root=true. I could have sworn that I didn't need that in the past. Anyway, nevermind. I know of no bugs right now.

**Comment by alex-courtis** [comment]
Thanks for updating. Unfortunately I'm not able to look at this until the weekend.

**Comment by emmanueltouzery** [comment]
no problem, thank you! In the meantime I'll keep using it through the week and be careful for glitches. As I said, I intend to use true+true for now, maybe i'll switch to quit_on_focus_loss=false+quit_on_open=true, I'll see.

**Review by alex-courtis — APPROVED** [review]
Tested OK.

Defaults match current behaviour.

Thanks for going the extra mile.

**Pull request merged**
