### PR TITLE
doc: add help wanted and contributing

### PR DESCRIPTION
**Pull request by alex-courtis**
Dealing with issues like #1318 is becoming very difficult.

### CODE REVIEW

**Comment by gegoune** [comment]
Auto labeling issues with respective OS labels based on value specified in issue might not be the worst idea. Then some volunteers could be auto mentioned. I am on macOS and willing to help according to my abilities.

**Review by kyazdani42 — APPROVED** [review]
let's do that first, we'll improve the bug triage as a 2nd step :)

**Comment by alex-courtis** [comment]
> Auto labeling issues with respective OS labels based on value specified in issue might not be the worst idea.

Nice! Could we do that with, say, a dropdown on the bug report form?

**Comment by gegoune** [comment]
I think so. Then https://github.com/actions/labeler could be used on issue: created event.

**Comment by alex-courtis** [comment]
Could you PR that?

The way to test a new form is to make the change on master of a fork or change the default branch of a fork.

**Comment by gegoune** [comment]
I am thinking whether auto labelling is a way to go here, as it not always is relevant. Most issues are platform independent and those that are platform specific should be labeled as such manually once it's established. I can come up with PR but after short reflection on the subject I no longer think it's a way forward - let me know your thoughts.

**Comment by alex-courtis** [comment]
Manual labelling works. Added 3 more "OS .*" labels.

Only a few issues actually need those labels.

**Pull request merged**
