### PR TITLE
fix(view): allow function for view.float.open_win_config

### LINKED ISSUE #1512: [Feature request] Allow floating window dimensions be customizable on demand
**Is your feature request related to a problem? Please describe.**

My use-case would be to open the float window in the center

**Describe the solution you'd like**

@alex-courtis proposes `view.float.open_win_config` to be a function that returns a table with the floating window configurations

**Describe alternatives you've considered**

Tried to calculate the values on entering neovim but with no luck:
```
local screen_w = vim.opt.columns:get()
local screen_h = vim.opt.lines:get() - vim.opt.cmdheight:get()
local _width = screen_w
local _height = screen_h
local width = math.floor(_width)
local height = math.floor(_height)
local center_y = (vim.opt.lines:get() - _height) / 2
local center_x = (screen_w - _width) / 2
```

**Additional context**

https://github.com/kyazdani42/nvim-tree.lua/pull/1462#issuecomment-1214272109

Thanks

### PR DESCRIPTION
**Pull request by alex-courtis**
resolves #1512

### CODE REVIEW

**Comment by alex-courtis** [comment]
- [ ] @davidsierradz please test

**Comment by davidsierradz** [comment]
Thanks! Tested and it works! Something that caught me off-guard is that I also need to define `view.width` and `view.height` to be functions, maybe add this to `view.float` docs?

This is what I have, for reference:

```
...
  view = {
    float = {
      enable = true,
      open_win_config = function()
        local screen_w = vim.opt.columns:get()
        local screen_h = vim.opt.lines:get() - vim.opt.cmdheight:get()
        local _width = screen_w * 0.7
        local _height = screen_h * 0.5
        local width = math.floor(_width)
        local height = math.floor(_height)
        local center_y = ((vim.opt.lines:get() - _height) / 2) - vim.opt.cmdheight:get()
        local center_x = (screen_w - _width) / 2
        local layouts = {
          center = {
            anchor = 'NW',
            relative = 'editor',
            border = 'single',
            row = center_y,
            col = center_x,
            width = width,
            height = height,
          },
        }
        return layouts.center
      end,
    },
    width = function()
      return math.floor(vim.opt.columns:get() * 0.7)
    end,
    height = function()
      return math.floor((vim.opt.lines:get() - vim.opt.cmdheight:get()) * 0.5)
    end,
  }
...
```

**Comment by alex-courtis** [comment]
> Something that caught me off-guard is that I also need to define `view.width` and `view.height` to be functions, maybe add this to `view.float` docs?

Interesting. Do view.width/height override `open_win_config`? Does that override occur if you set `open_win_config` to be a table?

If that's the case we should probably ignore view.width/height when floating. That will require deeper digging, as there are some other cases to consider, such as adaptive_width.

**Comment by davidsierradz** [comment]
> Interesting. Do view.width/height override open_win_config? Does that override occur if you set open_win_config to be a table?
Testing more, the problem seems to be only with `view.width`, for example:
```
require('nvim-tree').setup({
  view = {
    float = {
      enable = true,
      open_win_config = {
        relative = 'editor',
        height = 3,
        width = 3,
      },
    },
    width = 30,
    height = 30,
  },
})
```
Opens a float window with height=3 and width=30. Even if I remove `view.width`, float window opens with width=30 (so I guess is the default?)

**Comment by alex-courtis** [comment]
> Testing more, the problem seems to be only with `view.width`, for example:

Thank you. Raised #1543 with your workaround documented.

**Comment by kryzar** [comment]
Hi.

I hope this is the right place to ask this question; please tell me otherwise.

I used the code given in the comments to center my floating window.

nvim-tree-screen

```lua
require('nvim-tree').setup({
    hijack_cursor = true,
    actions = {
        open_file = {
            quit_on_open = true,
            window_picker = {
                enable = true,
            }
        }
    },
    diagnostics = {
        enable = true,
        show_on_dirs = true
    },
    filters = {
        dotfiles = true
    },
    renderer = {
        full_name = true,
        highlight_git = true,
        indent_width = 4,
    },
    tab = {
        sync = {
            open = true
        }
    },
    view = {
        float = {
            enable = true,
            -- Center the window
            -- Thanks https://github.com/nvim-tree/nvim-tree.lua/pull/1538
            open_win_config = function()
                local screen_w = vim.opt.columns:get()
                local screen_h = vim.opt.lines:get() - vim.opt.cmdheight:get()
                local _height = screen_h * 0.8
                local _width = screen_w * 0.8
                local width = math.floor(_width)
                local height = math.floor(_height)
                local center_y = ((vim.opt.lines:get() - _height) / 2)
                                 - vim.opt.cmdheight:get()
                local center_x = (screen_w - _width) / 2
                return {
                        anchor = 'NW',
                        relative = 'editor',
                        border = 'single',
                        row = center_y,
                        col = center_x,
                        width = width,
                        height = height,
                    }
                end,
        },
        width = function()
          return math.floor(vim.opt.columns:get() * 0.7)
        end,
        height = function()
          return math.floor((vim.opt.lines:get() - vim.opt.cmdheight:get()) * 0.5)
        end,
        adaptive_size = true,
        mappings = {
            custom_only = false,
            list = {
                { 
                    key = "l",
                    action = "edit",
                    action_cb = edit_or_open },
                { 
                    key = "L",
                    action = "vsplit_preview",
                    action_cb = vsplit_preview },
                { 
                    key = "h",
                    action = "close_node" },
                {
                    key = "H",
                    action = "collapse_all",
                    action_cb = collapse_all }
            }
        },
    },
})
```

Unfortunately, borders lost their radius. How can I add the original radius? Or even better, is there or will be a more automatic, better way to center the floating window?

Thanks a lot for this beautiful work.

**Comment by alex-courtis** [comment]
> I hope this is the right place to ask this question; please tell me otherwise.
No worries, we can discuss here. We can open an issue later if we'r looking at making changes.

That's quite a nice solution.

> Unfortunately, borders lost their radius. How can I add the original radius? Or even better, is there or will be a more automatic, better way to center the floating window?

Dumb question: are the borders losing their radius due to `border = 'single'`? We are defaulting them to `rounded`...

**Comment by kryzar** [comment]
> That's quite a nice solution. Perhaps you might add it to the wiki [Recipes](https://github.com/nvim-tree/nvim-tree.lua/wiki/Recipes) for others to use.

Sure, I'm happy to do it! I added a minor change to the code, deleting the
`view.height` attribute, as it lead to a warning at startup when the window was
narrow. As this key is not in the docs, I figures I'd just delete it.

screen-height-bug


I also deleted `view.float.open_win_config.anchor`, which didn't seem to be
affecting the code nor being mentioned in the docs.

If those changes are right for you then I can write the recipe. The complete code is:

```lua
local HEIGHT_RATIO = 0.8
local WIDTH_RATIO = 0.5

require('nvim-tree').setup({
    view = {
        float = {
            enable = true,
            open_win_config = function()
                local screen_w = vim.opt.columns:get()
                local screen_h = vim.opt.lines:get() - vim.opt.cmdheight:get()
                local window_w = screen_w * WIDTH_RATIO
                local window_h = screen_h * HEIGHT_RATIO
                local window_w_int = math.floor(window_w)
                local window_h_int = math.floor(window_h)
                local center_x = (screen_w - window_w) / 2
                local center_y = ((vim.opt.lines:get() - window_h) / 2)
                                 - vim.opt.cmdheight:get()
                return {
                    border = 'rounded',
                    relative = 'editor',
                    row = center_y,
                    col = center_x,
                    width = window_w_int,
                    height = window_h_int,
                }
                end,
        },
        width = function()
          return math.floor(vim.opt.columns:get() * WIDTH_RATIO)
        end,
    },
})
```

> Dumb question: are the borders losing their radius due to `border = 'single'`? We are defaulting them to rounded...

Hey no need to call my question dumb, let's keep this place civil! :) Sorry btw
for missing this option, and thanks a lot for solving the problem.

**Comment by gegoune** [comment]
> Dumb question: are the borders losing their radius due to border = 'single'? We are defaulting them to rounded...

> Hey no need to call my question dumb, let's keep this place civil! :) Sorry btw for missing this option, and thanks a lot for solving the problem.

I am pretty sure Alex meant his own question.

**Comment by kryzar** [comment]
> I am pretty sure Alex meant his own question.

Oh in that case I sincerely apologize for the misunderstanding. My bad.

**Comment by alex-courtis** [comment]
> Unfortunately, borders lost their radius. How can I add the original radius? Or even better, is there or will be a more automatic, better way to center the floating window?

I'm actually a little confused about how the border became rounded at all as your config should have always applied single.

It's working as expected now :shrug:

**Comment by kryzar** [comment]
As `border = 'rounded'` is the default, isn't it a bug that simply removing the `border` attribute renders this? Or am I mistaken?

Screenshot from 2022-12-04 12-29-56

**Comment by kryzar** [comment]
(Just a quick message to mention that I did not forget about the recipe; as I am very busy, I will write it at the end of the week.)

**Comment by alex-courtis** [comment]
> As `border = 'rounded'` is the default, isn't it a bug that simply removing the `border` attribute renders this? Or am I mistaken?

Of course. It's using vim default as the nvim-tree default table is completely removed.

**Comment by MostHated** [comment]
Hello all. My apologies if this is a silly question, I am still quite new to nvim. I have a question in regard to this floating window. If I pass a directory to neovim upon running it, I will get a nvim-tree, but it is not the floating one. If I hit my tree toggle command to hide it and then reopen it, it will show the floating one (demonstrated below). Is there something different I have to do, such as delaying the initial loading of the tree until after all of the settings have 'taken'?

https://user-images.githubusercontent.com/3442753/211436003-b6dec4cf-1efa-433b-9c46-fce2f40e0cdf.mp4

**Comment by alex-courtis** [comment]
> Hello all. My apologies if this is a silly question, I am still quite new to nvim. I have a question in regard to this floating window. If I pass a directory to neovim upon running it, I will get a nvim-tree, but it is not the floating one. If I hit my tree toggle command to hide it and then reopen it, it will show the floating one (demonstrated below). Is there something different I have to do, such as delaying the initial loading of the tree until after all of the settings have 'taken'?

That's a bug. Startup is problematic and experiences many race conditions.

A new mechanism is incoming: #1669

**Comment by pedro-psb** [comment]
I've found that when using the [`hjkl` recipe](https://github.com/nvim-tree/nvim-tree.lua/wiki/Recipes#h-j-k-l-style-navigation-and-editing), hitting `h` exits the floating window (`H` works fine). Any workaround suggestions?

And thanks, this feature is great :)

**Comment by gegoune** [comment]
Please open new issue (or discussion, more likely, as recipes from wiki aren't really "official") rather then commenting on months old pr.

**Pull request merged**
