### PR TITLE
fix: find file waits for git to finish

### LINKED ISSUE #969: [bug] gitignored files shown after folder is opened via find
**OS**
`Arch Linux 5.16.8-arch1-1`

**Neovim version**
```
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Nvim-tree version**
0f7da14

**Describe the bug**
When finding a file inside a closed directory, the directory is opened and the file caret set, hovewer the gitignored files are visible.

Upon refreshing the ignored files are hidden, however the caret is then on the incorrect file.

**To Reproduce**
empty nvim configuration, no plugins othen than nvim-tree
```
NvimTreeOpen
:e dir/file
NvimTreeFindFile
```

[asciicast](https://asciinema.org/a/468650)

**Expected behavior**
gitignored files should not be visible.

### LINKED ISSUE #970: Multiple Files Highlighted When Using update_focused_file
**OS**
`Arch Linux 5.16.8-arch1-1`

**Neovim version**
```
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Nvim-tree version**
0f7da14

**Describe the bug**
`update_focused_file.enabled` results in multiple files being highlighted when switching buffers.

**To Reproduce**
empty nvim configuration, no plugins othen than nvim-tree and chriskempson/base16-vim
```
tree.setup {
	update_focused_file = {
		enable = true,
	},
}
```
NvimTreeOpen
open some files via the tree
switch between buffers via `:b`
Multiple files are highlighted, with highlighting being removed when switching away from the most recently highlighted buffer.

[asciicast](https://asciinema.org/a/468654)

**Expected behavior**
Only one file should be highlighted: the active buffer's.

### PR DESCRIPTION
**Pull request by kyazdani42**
fixes #969
~might fix #970~ neovim bug

### CODE REVIEW

**Comment by kyazdani42** [comment]
@alex-courtis can you confirm it fixes these issues ?

**Comment by alex-courtis** [comment]
Still occurring at `fix/find-file` 79c0331

**Comment by kyazdani42** [comment]
@alex-courtis cannot reproduce although i can on the master branch. Are you sure you can still reproduce it ?

**Comment by alex-courtis** [comment]
Unfortunately still occurring:

```lua
tree.setup {
	update_focused_file = {
		enable = true,
	},
}
```

```sh
cd ~/.local/share/nvim/vundle/nvim-tree.lua
echo "*.obj" >> .gitignore
touch lua/nvim-tree/temporary.obj
vi
```

`:e lua/nvim-tree/colors.lua`
`:NvimTreeOpen`
temporary.obj is visible
`:NvimTreeRefresh`
temporary.obj not visible

**Comment by kyazdani42** [comment]
Well anyhow this fixes some things so i'll merge it :)

**Comment by alex-courtis** [comment]
@kyazdani42 my availability to work on nvim-tree fixes is half of Saturday and all of Sunday.

Is there a specific issue I should work on first? I'll look at #973 #969 #972 otherwise.

**Comment by kyazdani42** [comment]
Hi @alex-courtis, very nice of you :)
Just work on whatever seems better to you !

**Pull request merged**
