### PR TITLE
fix: replace vertsplit highlights (#1142)

### PR DESCRIPTION
**Pull request by siduck**
Replaced vertsplit hl groups with WinSeparator

### CODE REVIEW

**Comment by siduck** [comment]
image

works now! :D

image

**Review by kyazdani42 — APPROVED** [review]
thanks for the update :)

**Comment by par4m** [comment]
doesn't seem to work on v0.8

**Comment by alex-courtis** [comment]
> doesn't seem to work on v0.8

This was reverted due to #1221

New PR opened #1225. I would be grateful if you could test that branch before we merge.

**Pull request merged**
