### PR TITLE
#837 search subdirs

### PR DESCRIPTION
**Pull request by alex-courtis**
It is possible that I am missing the point, however it seems to me that search is not working.

Changes:
- rewrote to use filesystem search; node search was problematic and complex
- matches input that exactly matches the end of a path e.g. `file1` `dir1/` `dir1/file11` but not `ir1/file11` or `le11`
- adds `:find` style command line completion for all files under cwd

Resolves:
- bug in which searching would result in two nodes would be created for the same file

Does not:
- search under the current node; searches under cwd; this could be added

Exposed:
- find-file bug around symlinks #1093

### CODE REVIEW

**Review by kyazdani42 — APPROVED** [review]
indeed seemed like it wasn't working. Good idea to fallback to find_file

**Comment by be-ndee** [comment]
Okay, maybe I gave the action a miss leading name :-D A better name would have been "go to file". So my intention was that you can enter a path to jump to that directory/file in the tree. So you don't have to click or navigate through the whole tree. But "your" search is also a good feature. But it would be good, that the search checks the options for ignored files. Because I have a node_modules directory, which is in the gitignore and not visible for me in the tree, but the search searches in the node_modules, so it's quite slow.

**Comment by kyazdani42** [comment]
why not just using `/` then ? I don't understand the point of just moving the cursor to a file ? The search should not search inside ignored directories right ?

**Comment by alex-courtis** [comment]
> search checks the options for ignored files

That is a great idea, as the file system search indeed does not obey .gitignore etc.

Probably as an option: there are currently three "flavours" of ignored: git_ignored, dotfiles and custom. Perhaps obeying all three of those would be a "good enough" solution. There will be an elegant an simple solution, however will take some thinking about.

**Comment by alex-courtis** [comment]
Raised #1099

2 seems like a workable solution, however I have a feeling that there is something simpler.

**Comment by alex-courtis** [comment]
> why not just using `/` then

That matched the functionality of S when I was testing. Finding files in subdirectories was not working.

It seems that I was misunderstanding the purpose of S. Please accept my apologies @be-ndee

**Pull request merged**
