### PR TITLE
Add screenshot4.png

### PR DESCRIPTION
**Pull request by reyhankaplan**
Hey @kyazdani42, thanks for the great plugin. I don't know if screenshot PRs are acceptable but this is my setup right now. Thanks again.

### CODE REVIEW

**Comment by Adnios** [comment]
Hey. Awesome screenshot. I have a question. How to highlight the current edited file in nvim-tree with cursorline when cursor in file.
image

**Comment by reyhankaplan** [comment]
Hi @Adnios, thank you so much. I believe what you are looking for is [update_focused_file](https://github.com/kyazdani42/nvim-tree.lua/blob/5d8453dfbd34ab00cb3e8ce39660f9a54cdd35f3/doc/nvim-tree-lua.txt#L183-L202) option. Don't forget to check whether or not `'cursorline'` is `true` for nvim-tree window.

**Comment by alienxp03** [comment]
@reyhankaplan Hope you don't mind me reviving an old PR to ask a question. In your setup, how did you manage to show the list of open files there? Referring to `settings.lua`, `mappings.lua`, & `nvim_tree.lua` on the right panel. I've tried with `tabnew`, but it seems like a different behavior.

**Comment by reyhankaplan** [comment]
Hi @alienxp03, that can be achieved with this amazing [bufferline](https://github.com/akinsho/bufferline.nvim) plugin. It's basically an enchantment over native tabline. I highly recommend it.

Feel free to ask me if you have any other questions. Have a good day!

**Comment by alienxp03** [comment]
Awesome. Thanks @reyhankaplan!

**Pull request merged**
