### PR TITLE
Optionally suppress the symlink destination

### PR DESCRIPTION
**Pull request by tobywan**
Setting `nvim-tree.renderer.symlink_destination=false` will prevent the arrow and symlink `link_to` file
appearing in the tree.
The original symlink name, icons and colour are not affected.

This is useful when `nvim-tree.view.adaptive_size = true`, because the full path of the `node.link_to` is used which can mean that the tree window is excessively large for files deep in the file system.
Compare:
symlink_destination-true

symlink_destination-false

### CODE REVIEW

**Comment by kyazdani42** [comment]
@tobywan looks good to me, just fix the style :)

**Comment by tobywan** [comment]
Thanks, I pushed a 3rd commit that _should_ have fixed it. Is your comment after that push?

**Comment by kyazdani42** [comment]
yes, check the CI :) there is a missing space before the `..`

**Comment by tobywan** [comment]
> yes, check the CI :) there is a missing space before the `..`

D'Oh!
My bad, spotted the extra leading space but missed that one.

**Comment by alex-courtis** [comment]
Not able to review right now, however this is a fantastic option that I will definitely use.

**Review by kyazdani42 — APPROVED** [review]

**Pull request merged**
