### PR TITLE
1050 sync defaults

### PR DESCRIPTION
**Pull request by alex-courtis**
Review / merge https://github.com/kyazdani42/nvim-tree.lua/pull/1051 first.

Script that scrapes DEFAULT_OPTS and updates readme, help and issue template.

Did not do the same for legacy g: options as they will go away.

Uses comments as markers in lua and markdown, uses hacky pattern matching in yml and help.

### CODE REVIEW

**Comment by kyazdani42** [comment]
hi ! Could you edit the missing defaults that were defined in the docs before ? also rebase the bug_report template :)

**Comment by alex-courtis** [comment]
> hi ! Could you edit the missing defaults that were defined in the docs before ? also rebase the bug_report template :)

Yes, this PR is out of date already. Once #1050 is rebased / merged I will do the same here.

**Comment by kyazdani42** [comment]
thanks for the hard work :)

**Comment by alex-courtis** [comment]
Thank you for the plugin.

My aim is to provide support so that you may develop the plugin faster.

**Comment by alex-courtis** [comment]
superceeded by #1074

**Pull request closed without merging**
